# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'crossword-maker' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for crossword-maker
  pod 'Alamofire'
end
